# Generated by Django 5.0.4 on 2024-06-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eblog", "0005_alter_blog_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_file", models.FileField(upload_to="videos/")),
                ("name", models.TextField(verbose_name="Название видео")),
            ],
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(upload_to="images/", verbose_name="Картинка"),
        ),
    ]
