# Generated by Django 5.0.4 on 2024-06-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eblog", "0007_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="username",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
    ]
