# Generated by Django 5.0.4 on 2024-06-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eblog", "0008_alter_feedback_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=250),
        ),
    ]
